### ISSUE TITLE
Requires `vim-eunuch`

### ISSUE THREAD

**Issue by rjmk** [chkno/vim-haskell-module-name#5]
To reproduce:

Using a vim without `vim-eunuch` installed, execute `FixHaskellFilename`. The editor will complain about `Move` not being an editor command. This is because it's introduced by `vim-eunuch`.

Not sure what the proper fix is -- possibly just documentation?

**Comment by rjmk** [comment]
And there already is documentation! Derp. Perhaps something could be done to make the dependency more obvious, but seems like the situation should still mean a closed issue

**Comment by chkno** [comment]
It looks like the vim-plugin community hasn't yet figured out how to manage dependencies between vim plugins: https://junegunn.kr/2013/09/thoughts-on-vim-plugin-dependency .

* Plug added and later [removed](https://github.com/junegunn/vim-plug/issues/43) a way to specify dependencies only worked with Plug.
* The [plugin index](https://github.com/MarcWeber/vim-addon-manager-known-repositories) hasn't been updated since 2015.
*  vim-flavor has [a way](https://relishapp.com/kana/vim-flavor/docs/flavorfile/version-constraint) to specify dependencies that only works with vim-flavor.
* "apt-vim" has [a terrible way](https://vimawesome.com/plugin/apt-vim#summary) to specify dependencies that only works with apt-vim, and is built on pathogen which disrecommends itself.

Sorry.  :(

**Comment by rjmk** [comment]
Possibly could use `exists(":Move")`, and then throw an error with more guidance as to what went wrong

**Comment by chkno** [comment]
Good point.  Done in f9f8e9f83a30b8f805b8fbc0079163e8193b289b.  Thanks!
